### ISSUE TITLE
build failed (flare_flutter/lib/flare.dart:1023)

### ISSUE THREAD

**Issue by langhuihui** [2d-inc/developer_quest#142]
file:///C:/Users/17080854/AppData/Roaming/Pub/Cache/git/Flare-Flutter-4aebb0ff5b98c7bcf2183c6bac8226cc7ddf5402/flare_flutter/lib/flare.dart:1023:18: Error: The argument type 'Int32List' can't be assigned to the parameter type 'Uint16List'.
 - 'Int32List' is from 'dart:typed_data'.
 - 'Uint16List' is from 'dart:typed_data'.
Try changing the type of the parameter, or casting the argument to 'Uint16List'.
        indices: _indices, textureCoordinates: _uvBuffer);

**Comment by brotherOfChina** [comment]
I also encountered such a problem, hope to be solved

**Comment by luigi-rosso** [comment]
Hello, 

This error is due to a breaking change with Flutter master/dev. You are likely using one of those two channels. If you are trying to run the code in this repository, please use the Flutter stable branch by typing this into your terminal:

```
flutter channel stable
flutter upgrade
```

This is the easiest fix that should get you running very quickly. Alternatively, if you're adventurous, you can try to update the code to use a newer version of Flare (which is compatible with Flutter master/dev) by pointing the Flare-Flutter dependency to the dev branch in GitHub as follows:

```
flare_flutter:
  git: 
    url: git://github.com/2d-inc/Flare-Flutter.git
    ref: dev
    path: flare_flutter
```

We have details about how to do this in our Flare-Flutter readme here:
https://github.com/2d-inc/Flare-Flutter

Various other reports of this issue which contain more info, in case anything here is not clear:
https://github.com/2d-inc/Flare-Flutter/issues/79#issuecomment-486220048
https://github.com/2d-inc/Flare-Flutter/issues/105
https://github.com/2d-inc/Flare-Flutter/issues/98
https://github.com/2d-inc/Flare-Flutter/issues/94
https://github.com/2d-inc/Flare-Flutter/issues/86

**Comment by langhuihui** [comment]
Thank you,it's working!

**Comment by twovs** [comment]
flare_flutter:
  git: 
    url: git://github.com/2d-inc/Flare-Flutter.git
    ref: dev
    path: flare_flutter


I Use this ,but it's not runing :p
